### PR TITLE
feat: downgrade api 1.3 to 1.2

### PR DESCRIPTION
**Pull request by tribiec**
This PR downgrades the API version from 1.3 to 1.2 and also removes some specific methods used on version 1.3.

### CODE REVIEW

**Review by mastudillot — APPROVED** [review]
LGTM

**Comment by Matiasnickolas** [comment]
Commits should use a short lead token, like **_refactor_**, **_feat_**, etc.
Modifications to changelog should be added on the prepare release branch

**Review by mastudillot — APPROVED** [review]
LGTM

**Review by mvarlic — APPROVED** [review]
LGTM!

**Pull request merged**
